### ISSUE TITLE
Scots Pine is unrealistic

### ISSUE THREAD

**Issue by frogocomics** [frogocomics/OpenTrees#17]
wunder_bread, sorry to say this, but I think Scots Pine is inaccurate to what it should really look like.
![screenshot_2](https://cloud.githubusercontent.com/assets/10662167/13860556/30eba146-ec46-11e5-81ff-6beccbcf2871.png)
![scots pine](https://upload.wikimedia.org/wikipedia/commons/3/31/A_trio_of_Scots_Pine_-_geograph.org.uk_-_1750728.jpg)
To make it more realistic, it should be made taller, and there should be no leaves in the bottom half. The large variant should be made around 40 blocks tall (Source: [https://en.wikipedia.org/wiki/Scots_pine](url)). Normally I wouldn't say anything like this, but it can certainty be made better!

**Pro tip: Dark oak fences can reassemble small branches**

**Comment by wunder-bread** [comment]
It's all good. I'll fix them. I was referencing a different pic.
![scots-pine3](https://cloud.githubusercontent.com/assets/17827326/13861658/d3827470-ec64-11e5-8ceb-67cad44c6f6d.jpg)
![scots-pine](https://cloud.githubusercontent.com/assets/17827326/13861659/d99109b2-ec64-11e5-9861-336ca14777ae.jpg)

**Comment by frogocomics** [comment]
Remember to make wikipedia your first source for now. Its true that trees can look very different sometimes, even though they are of the same speices!

**Comment by wunder-bread** [comment]
@frogocomics  This is just a very rough draft. Something more along these lines?

**Comment by wunder-bread** [comment]
![2016-03-18_15 19 41](https://cloud.githubusercontent.com/assets/17827326/13889428/e88aac30-ed1c-11e5-9db0-af81ac1c9409.png)

**Comment by frogocomics** [comment]
More leaves on the top.

**Comment by frogocomics** [comment]
Thanks again for your contributions by the way :smile:

**Comment by wunder-bread** [comment]
feedback appreciated.
![scots](https://cloud.githubusercontent.com/assets/17827326/13924829/3301b95c-ef5c-11e5-857b-e771cc7ec9c1.png)

**Comment by frogocomics** [comment]
Don't make it so sharp on the top. (Break the topmost 2 blocks)

**Comment by wunder-bread** [comment]
@frogocomics  I'll have all the scots pine files up by this evening. Playing catch up on a ton of other things.

**Comment by frogocomics** [comment]
Thanks again.
