### ISSUE TITLE
Create Demo Maps and Renders Utilitizing Trees

### ISSUE THREAD

**Issue by frogocomics** [frogocomics/OpenTrees#21]
This tree pack is nearing its release, so I started making renders of 512 x 512 maps, using some trees. I rendered the map using cinema4d. I was hoping wunder-bread could help me with this: you said you had cinema4d.

**Comment by wunder-bread** [comment]
@frogocomics yes, i do. skype me, will be easier to sort out.

**Comment by frogocomics** [comment]
What is your skype?

**Comment by wunder-bread** [comment]
my bad. wunder_bread
it will have a Knight Templar avatar

**Comment by wunder-bread** [comment]
I'm trying. But my network has been in constant use this past week. And the render sizes you want done are huge. I think all that detail is being lost to the average user that is viewing them on a dell laptop.

**Comment by frogocomics** [comment]
Yeah I know, thinking about doing 1080p renders now.
