### ISSUE TITLE
Create More European Trees

### ISSUE THREAD

**Issue by frogocomics** [frogocomics/OpenTrees#22]
As I want to release this pack to the public soon, I hope that more trees from [https://en.wikipedia.org/wiki/List_of_trees_of_Great_Britain_and_Ireland](this list) be built.

**Comment by wunder-bread** [comment]
![capture](https://cloud.githubusercontent.com/assets/17827326/14049646/f31ebffe-f28c-11e5-87ac-b34993f2577c.PNG)
 This is the list I am working on now.

**Comment by frogocomics** [comment]
Thanks!

**Comment by frogocomics** [comment]
There is no need to be rushed, by the way: we can focus on quality :D

**Comment by frogocomics** [comment]
If you want to create a shrub with flowers, you can use WorldEdit/McEdit to add Minecraft flowers on top of the leaves.
[https://github.com/frogocomics/OpenTrees/blob/master/Images/Cornus%20sanguinea%20L1.png](Image)

**Comment by wunder-bread** [comment]
Can also use the no physics brush with voxel sniper

**Comment by wunder-bread** [comment]
Currently working on the Downy Birch, the Euro Birch, and the Blackthorn
