### ISSUE TITLE
Species names too specific?

### ISSUE THREAD

**Issue by alchzh** [frogocomics/OpenTrees#24]
Within genuses, sometimes many trees are very similar to each other (even within families). With the low resolution that minecraft offers, it is pointless to distinguish these trees. For example, Fraxinus excelsior (common ash) vs Fraxinus angustifolia (narrow-leafed ash). The differences are related to leaves and buds, which obviously has no difference in MC. Why not just make a section called, ash version one or something instead of calling it "Fraxinus Excelsior"?

**Comment by frogocomics** [comment]
My idea is to basically not build 2 types of trees within the same genus. I understand your idea, I'll just build less trees of the same genus.

**Comment by wunder-bread** [comment]
I agree with @acz13 . Also how many kids are going to recognize latin names? I think a better naming scheme would benefit the project. (especially one with no spaces in the file name)

**Comment by frogocomics** [comment]
My idea is to include a chart on Planet Minecraft or a powerpoint showing the conversion from the latin name to the common name. I just believe that the scientific name can make the plants more clear (more specific).
