### ISSUE TITLE
Starting website...

### ISSUE THREAD

**Issue by alchzh** [frogocomics/OpenTrees#27]
So school decided to be a little lenient (finally) and I have time to do a website!

Post like any ideas here...

**Comment by frogocomics** [comment]
A way to organize schematics

**Comment by wunder-bread** [comment]
A way to better name the .schematics also. Those file names make working with them in game asinine. I already renamed all of them locally for my personal use.

**Comment by frogocomics** [comment]
Wunder, perhaps show the common name of the tree as a display name in the website?

**Comment by wunder-bread** [comment]
That also. But we need to shorten the file name itself (and no spaces, so you don't have to wrap it ).  Typing this in game is a pain in the ass...  
"Ulmus minor subsp. minor S2.schematic" I just named them ulmus1.schematic  1-6, by size. If there are 2 trees in the same Genus, then i use the first letter of the species. i.e - quercusp1, quercusr1 ... and so on.
And definitely use the common name of the trees on the website. I really think people (especially younger users) will be put off by it being over complicated.

**Comment by frogocomics** [comment]
Wunder how about scientific name (common name).schematic

**Comment by frogocomics** [comment]
acz13, could you commit the website to the gh-pages branches so it will be hosted on frogocomics.github.io?

**Comment by wunder-bread** [comment]
@frogocomics  , doesn't matter to me. Anything shorter than it is, and NO spaces.

**Comment by alchzh** [comment]
@frogocomics working on it... I'm trying to wrestle to github API to get stuff

**Comment by alchzh** [comment]
Almost done... commit should be soon

**Comment by alchzh** [comment]
@frogocomics sorry I've been on vacation for like 2 weeks but...

I don't really think github would be very good for this... the javascript pulling from the API is just a mess. I'm sure I could work out a simple server thing... problem is I don't have a server to spare... heh. What do you think?

**Comment by frogocomics** [comment]
Do you speak of ftp?

**Comment by frogocomics** [comment]
@acz13 Sorry, I have little knowledge of this field. But I do have a ftp server because I ordered a mc server

**Comment by alchzh** [comment]
No I'm talking about any webserver. I could set up a system where users would be able to submit schematics and we (you) could accept them. That would also make organizing the trees much easier.

basically not use github for hosting but our own server

**Comment by frogocomics** [comment]
Yep, that could work. I might be able to contribute small amounts of money ($5) for hosting or whatever, not rich or anything.

**Comment by alchzh** [comment]
nevermind that for now, I'll finish a client side GH repo API rn
