### ISSUE TITLE
Example Terrain Needed!

### ISSUE THREAD

**Issue by frogocomics** [frogocomics/OpenTrees#29]
I'm almost ready to present OpenTrees to the world, and I would love it if someone made terrain using OpenTrees and rendering it using software.

**Comment by wunder-bread** [comment]
who is someone?

**Comment by frogocomics** [comment]
Whoever wants to :)

**Comment by wunder-bread** [comment]
No time here. We just released the 1.9 version of the conquest mod last week, our server is up, and the website is being coded.

**Comment by frogocomics** [comment]
It's okay. My bud ajthemacboy will be making a 1k.
