### ISSUE TITLE
STL Files

### ISSUE THREAD

**Issue by alchzh** [frogocomics/OpenTrees#7]
Github has support for viewing STL files in browser. I think it'd be nice to have STLs for the trees so people can view them in 3D from Github. What do you think?

**Comment by frogocomics** [comment]
I would start doing that when I have time, or maybe you could do it?  [http://www.jmc2obj.net/](http://www.jmc2obj.net/) can export parts of a world into a stl, I believe. Right now I my main focus is building and rendering trees.
