### ISSUE TITLE
Render sizes too large?

### ISSUE THREAD

**Issue by alchzh** [frogocomics/OpenTrees#8]
ATM `images.md` is really.... slow... to... load.... Maybe we could resize the renders to a smaller size?

**Comment by frogocomics** [comment]
I'll take care of that. I will make a new folder called thumbnails, and you can modify your code so it loads the thumbnails instead of the full size images.

**Comment by frogocomics** [comment]
Could you modify your Python script so that it will take images from the Thumbnails folder?

**Comment by alchzh** [comment]
Could you trim the edge off the images? They're still large...

**Comment by frogocomics** [comment]
Should I resize all the images to 600 x 400? I can't trim because I am using a mass image resizer.

**Comment by frogocomics** [comment]
Also, on a site note, are you able to help with the branch gh-pages?

**Comment by alchzh** [comment]
Yeah ofc.

**Comment by frogocomics** [comment]
https://www.reddit.com/r/Worldpainter/comments/4aduu6/an_tree_repository_anyone_can_contribute_to/ 
You might want to look at what lentebrijse has to say...

**Comment by alchzh** [comment]
I could do that, however, I don't have a webserver at the ready...

**Comment by frogocomics** [comment]
frogocomics.github.io, that is the current url, for the gh-pages site

**Comment by alchzh** [comment]
I'm talking about /u/lentebrijse has to say. You can't make that a static site (github)

**Comment by frogocomics** [comment]
Well, my MC server host has free webhosting, and I could buy a domain :D
