### ISSUE TITLE
All Trees should be converted into .bo2 files

### ISSUE THREAD

**Issue by frogocomics** [frogocomics/OpenTrees#9]
Someone trees, those after wunder-bread's commit, have not been converted into BO2.

**Comment by alchzh** [comment]
Why not BO3? then we could use [BO3Tools](http://dev.bukkit.org/bukkit-plugins/bo3tools/)  
NVM we should just be able to use [s2b](https://github.com/MCTCP/TerrainControl/wiki/s2b-by-MassiveCraft)

**Comment by wunder-bread** [comment]
Converted
